# Generated by Django 5.2 on 2025-08-03 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0003_alter_timelog_end_time_alter_timelog_task'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='version',
        ),
        migrations.RemoveField(
            model_name='task',
            name='project_version',
        ),
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='projects', to='project.client'),
        ),
        migrations.AlterField(
            model_name='project',
            name='collabolators',
            field=models.ManyToManyField(blank=True, related_name='collaborated_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
