# Generated by Django 5.2 on 2025-09-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('project', '0004_remove_project_version_remove_task_project_version_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(
                choices=[('active', 'Aktywny'), ('completed', 'Ukończony'), ('paused', 'Wstrzymany')], default='active',
                max_length=9),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Niski'), ('medium', 'Średni'), ('high', 'Wysoki')],
                                   default='medium', max_length=6),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(
                choices=[('to_do', 'Do zrobienia'), ('in_progress', 'W trakcie'), ('completed', 'Ukończony')],
                default='to_do', max_length=11),
        ),
    ]
