# Generated by Django 5.2 on 2025-07-27 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_profile_picture_friend_friendrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='friends',
            field=models.ManyToManyField(
                related_name='friend_of',
                to=settings.AUTH_USER_MODEL),
        ),
    ]

